# Deciding Headquarters
## Data Analysis on Headquarters
This is where I will do the work to try and analyze where headquarters should be.

In [8]:
import pandas as pd

df_contracts = pd.read_csv('../data/contracts.csv') 
df_customers = pd.read_csv('../data/customers.csv') 
df_customers.rename(columns={'id': 'customer_id'}, inplace=True)
df_customers.rename(columns={'id': 'cusotmer_id'}, inplace=True)
df_contracts = df_contracts.set_index('customer_id')

df = df_contracts.join(df_customers, how='left')
df.head(25)

,contract_id,contract_start,contract_term,deposit,monthly_amt,customer_id,company,sector,industry,email,address,city,state,zip
1,41,5/31/2019,24,"$86,000.00","$11,200.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,358,6/18/2019,13,"$74,000.00","$19,000.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,400,8/11/2019,19,"$38,000.00","$8,800.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,424,3/13/2019,15,"$77,000.00","$14,300.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,438,10/16/2019,22,"$39,000.00","$20,000.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,657,8/27/2019,24,"$67,000.00","$22,400.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,848,11/15/2019,11,"$34,000.00","$10,700.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
2,308,3/28/2019,24,"$14,000.00","$6,900.00",3,Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
2,416,12/25/2019,18,"$63,000.00","$8,900.00",3,Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
2,645,9/20/2019,3,"$34,000.00","$19,100.00",3,Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
2,754,11/15/2019,12,"$76,000.00","$6,600.00",3,Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
2,954,1/31/2019,14,"$15,000.00","$24,300.00",3,Twitterworks,NaN,NaN,alerohan2@ox.ac.uk,29 Hovde Hill,Milwaukee,WI,53234
3,361,8/11/2019,1,"$49,000.00","$17,900.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
3,596,12/1/2019,1,"$19,000.00","$13,500.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
3,603,2/8/2019,7,"$76,000.00","$7,900.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
3,759,6/3/2019,9,"$91,000.00","$10,900.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
3,953,3/7/2019,18,"$38,000.00","$9,900.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
3,1000,3/19/2019,16,"$23,000.00","$15,700.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
4,378,12/10/2019,24,"$46,000.00","$15,700.00",5,Jabberstorm,Technology,Computer Software: Prepackaged Software,pscallon4@fc2.com,4 Moose Way,Terre Haute,IN,47805
4,525,1/8/2019,15,"$50,000.00","$24,500.00",5,Jabberstorm,Technology,Computer Software: Prepackaged Software,pscallon4@fc2.com,4 Moose Way,Terre Haute,IN,47805
4,896,2/5/2019,18,"$85,000.00","$5,600.00",5,Jabberstorm,Technology,Computer Software: Prepackaged Software,pscallon4@fc2.com,4 Moose Way,Terre Haute,IN,47805
5,501,10/23/2019,5,"$75,000.00","$19,300.00",6,Teklist,Technology,Radio And Television Broadcasting And Communic...,kformigli5@symantec.com,085 Messerschmidt Street,San Antonio,TX,78245
5,707,5/23/2019,6,"$46,000.00","$19,600.00",6,Teklist,Technology,Radio And Television Broadcasting And Communic...,kformigli5@symantec.com,085 Messerschmidt Street,San Antonio,TX,78245
6,11,12/7/2019,4,"$26,000.00","$19,100.00",7,Meedoo,NaN,NaN,ediscombe6@epa.gov,38 Shoshone Lane,El Paso,TX,79994
6,26,3/3/2019,17,"$69,000.00","$19,400.00",7,Meedoo,NaN,NaN,ediscombe6@epa.gov,38 Shoshone Lane,El Paso,TX,79994

In [2]:
df.groupby('state').agg({'contract_id':'count', 'company':pd.Series.nunique}).sort_values('company', ascending=False)

       contract_id  company
state
TX             110       20
CA              83       16
FL              73       15
NY              58       11
WA              38        9
DC              27        8
KS              34        7
PA              36        7
VA              28        7
LA              32        6
OH              37        6
WI              31        6
CO              30        6
OK              25        5
OR              31        5
AZ              22        5
MO              25        5
MI              16        4
NC              23        4
GA              15        4
MD              19        4
TN              26        4
IL              22        4
NE              12        3
ID              10        3
DE              18        3
IN              10        3
MN              18        3
CT              10        2
NV              15        2
SC               5        1
AK               7        1
NM               7        1
NJ               5        1
MS               1        1
AL               6        1
ME              10        1
MA              10        1
KY               3        1
AR               6        1
WV               6        1

In [3]:
df.loc[df['state']=='CT']

,contract_id,contract_start,contract_term,deposit,monthly_amt,customer_id,company,sector,industry,email,address,city,state,zip
135,15,7/11/2019,14,"$41,000.00","$23,700.00",136,Eabox,Energy,Coal Mining,eway3r@shinystat.com,9002 Northwestern Center,Hartford,CT,6160
135,581,11/27/2019,14,"$59,000.00","$18,400.00",136,Eabox,Energy,Coal Mining,eway3r@shinystat.com,9002 Northwestern Center,Hartford,CT,6160
135,698,11/25/2019,3,"$13,000.00","$6,500.00",136,Eabox,Energy,Coal Mining,eway3r@shinystat.com,9002 Northwestern Center,Hartford,CT,6160
135,890,8/21/2019,21,"$18,000.00","$12,400.00",136,Eabox,Energy,Coal Mining,eway3r@shinystat.com,9002 Northwestern Center,Hartford,CT,6160
135,939,4/5/2019,19,"$80,000.00","$9,500.00",136,Eabox,Energy,Coal Mining,eway3r@shinystat.com,9002 Northwestern Center,Hartford,CT,6160
186,80,3/11/2019,15,"$63,000.00","$22,100.00",187,Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
186,412,12/28/2019,7,"$65,000.00","$16,000.00",187,Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
186,458,12/2/2019,2,"$90,000.00","$13,200.00",187,Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
186,826,12/29/2019,7,"$38,000.00","$21,800.00",187,Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912
186,870,7/16/2019,10,"$60,000.00","$17,300.00",187,Jaloo,Miscellaneous,Business Services,lmessent56@blogs.com,094 Derek Road,Stamford,CT,6912

In [4]:
df.loc[df['contract_term'] < 2]

,contract_id,contract_start,contract_term,deposit,monthly_amt,customer_id,company,sector,industry,email,address,city,state,zip
3,361,8/11/2019,1,"$49,000.00","$17,900.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
3,596,12/1/2019,1,"$19,000.00","$13,500.00",4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667
15,84,4/4/2019,1,"$65,000.00","$22,600.00",16,Kwinu,NaN,NaN,alabetf@gov.uk,688 La Follette Park,Buffalo,NY,14215
15,105,1/31/2019,1,"$61,000.00","$20,200.00",16,Kwinu,NaN,NaN,alabetf@gov.uk,688 La Follette Park,Buffalo,NY,14215
16,211,6/15/2019,1,"$34,000.00","$14,200.00",17,Plambee,Consumer Durables,Building Products,laupolg@earthlink.net,82 Bobwhite Point,Colorado Springs,CO,80915
21,309,12/9/2019,1,"$44,000.00","$22,700.00",22,Jabbercube,Health Care,Biotechnology: In Vitro & In Vivo Diagnostic S...,cgentlel@cnn.com,8275 Arizona Street,Odessa,TX,79764
22,503,11/10/2019,1,"$64,000.00","$20,400.00",23,Feedfire,Consumer Durables,Industrial Specialties,rrobynsm@ca.gov,777 La Follette Center,Saint Paul,MN,55114
22,548,7/13/2019,1,"$55,000.00","$5,300.00",23,Feedfire,Consumer Durables,Industrial Specialties,rrobynsm@ca.gov,777 La Follette Center,Saint Paul,MN,55114
29,677,8/22/2019,1,"$24,000.00","$20,400.00",30,Skyba,Consumer Services,Real Estate Investment Trusts,sfussent@skype.com,49623 Thompson Plaza,Miami Beach,FL,33141
40,142,10/19/2019,1,"$25,000.00","$24,800.00",41,Feedspan,Finance,Finance: Consumer Services,adauby14@soundcloud.com,633 Emmet Drive,Oakland,CA,94605
51,628,7/8/2019,1,"$67,000.00","$24,000.00",52,Jabbertype,NaN,NaN,ycole1f@facebook.com,859 Summer Ridge Alley,Topeka,KS,66642
52,556,6/12/2019,1,"$53,000.00","$8,600.00",53,Centidel,Finance,Major Banks,fsutherby1g@reuters.com,93 Melvin Park,San Francisco,CA,94164
53,473,5/10/2019,1,"$22,000.00","$8,100.00",54,JumpXS,Consumer Services,RETAIL: Building Materials,ljarville1h@zdnet.com,8 Pennsylvania Trail,Gaithersburg,MD,20883
55,393,6/3/2019,1,"$60,000.00","$22,400.00",56,Twitternation,Finance,Finance: Consumer Services,nchillingsworth1j@mysql.com,8 Donald Plaza,Lansing,MI,48956
55,653,11/28/2019,1,"$77,000.00","$5,500.00",56,Twitternation,Finance,Finance: Consumer Services,nchillingsworth1j@mysql.com,8 Donald Plaza,Lansing,MI,48956
60,23,7/13/2019,1,"$29,000.00","$21,400.00",61,Bubblemix,Consumer Services,Real Estate Investment Trusts,rarlt1o@seattletimes.com,5498 Steensland Point,Shawnee Mission,KS,66276
62,486,10/7/2019,1,"$68,000.00","$24,900.00",63,Camimbo,Consumer Services,Homebuilding,gkellaway1q@nifty.com,545 Anderson Street,Las Vegas,NV,89166
62,964,6/3/2019,1,"$37,000.00","$17,700.00",63,Camimbo,Consumer Services,Homebuilding,gkellaway1q@nifty.com,545 Anderson Street,Las Vegas,NV,89166
64,186,3/11/2019,1,"$57,000.00","$23,100.00",65,Avamm,Technology,Advertising,gpavyer1s@discuz.net,81 Ludington Way,Atlanta,GA,31119
66,301,12/9/2019,1,"$14,000.00","$15,700.00",67,Skinix,Technology,Semiconductors,ilernihan1u@friendfeed.com,142 Towne Road,Fort Worth,TX,76105
70,352,3/24/2019,1,"$37,000.00","$17,900.00",71,Thoughtstorm,Consumer Services,Services-Misc. Amusement & Recreation,mwilliams1y@e-recht24.de,65 Tony Plaza,Miami,FL,33129
70,665,9/27/2019,1,"$22,000.00","$24,300.00",71,Thoughtstorm,Consumer Services,Services-Misc. Amusement & Recreation,mwilliams1y@e-recht24.de,65 Tony Plaza,Miami,FL,33129
77,448,10/27/2019,1,"$62,000.00","$16,400.00",78,JumpXS,NaN,NaN,dphette25@foxnews.com,973 Ridgeway Pass,Columbus,OH,43268
80,758,1/24/2019,1,"$28,000.00","$7,000.00",81,Gigazoom,Consumer Services,Hotels/Resorts,oscoates28@cnet.com,21814 Waubesa Plaza,Oklahoma City,OK,73109
81,656,2/1/2019,1,"$45,000.00","$15,700.00",82,Edgeify,NaN,NaN,dcoolahan29@vistaprint.com,22 Anniversary Pass,Raleigh,NC,27635
83,420,4/15/2019,1,"$71,000.00","$12,000.00",84,Photojam,NaN,NaN,jbosward2b@china.com.cn,237 Farmco Street,Chicago,IL,60624
83,956,8/18/2019,1,"$43,000.00","$21,400.00",84,Photojam,NaN,NaN,jbosward2b@china.com.cn,237 Farmco Street,Chicago,IL,60624
88,374,5/1/2019,1,"$32,000.00","$7,000.00",89,Miboo,Technology,Semiconductors,ckirtley2g@ucoz.com,86234 Moland Point,Olympia,WA,98506
92,760,12/28/2019,1,"$31,000.00","$23,900.00",93,Bluezoom,Public Utilities,Telecommunications Equipment,ybrickhill2k@whitehouse.gov,19 Vidon Place,Pasadena,CA,91186
93,375,3/16/2019,1,"$39,000.00","$8,000.00",94,Aivee,Public Utilities,Telecommunications Equipment,wlidden2l@earthlink.net,19 Portage Parkway,Muncie,IN,47306
95,85,8/13/2019,1,"$17,000.00","$21,700.00",96,Devify,Finance,Major Banks,apittman2n@i2i.jp,0 Stoughton Street,Schenectady,NY,12325
96,257,7/2/2019,1,"$96,000.00","$23,200.00",97,Photospace,Consumer Services,Services-Misc. Amusement & Recreation,tgibbin2o@dion.ne.jp,314 Kim Junction,Seattle,WA,98166
98,776,7/12/2019,1,"$86,000.00","$20,900.00",99,Linktype,Technology,EDP Services,jlackner2q@gmpg.org,6721 Kenwood Lane,Pittsburgh,PA,15279
107,278,4/21/2019,1,"$94,000.00","$17,400.00",108,Feedspan,Consumer Non-Durables,Electronic Components,mmacgowan2z@unicef.org,4964 Muir Lane,New York City,NY,10165
111,132,8/14/2019,1,"$93,000.00","$6,000.00",112,Dablist,NaN,NaN,kcushion33@statcounter.com,09 Waubesa Hill,Tampa,FL,33633
121,491,11/6/2019,1,"$12,000.00","$9,600.00",122,Skinder,Health Care,Major Pharmaceuticals,cstuttard3d@businesswire.com,7 Chive Drive,Schenectady,NY,12305
128,248,3/17/2019,1,"$19,000.00","$6,300.00",129,Edgetag,NaN,NaN,hwinship3k@rediff.com,32 Pennsylvania Point,Las Vegas,NV,89155
129,388,5/9/2019,1,"$59,000.00","$8,200.00",130,Gabvine,Health Care,Medical/Dental Instruments,iburgwyn3l@umn.edu,8557 Myrtle Trail,New York City,NY,10029
131,492,5/22/2019,1,"$81,000.00","$13,200.00",132,Flashspan,Finance,Savings Institutions,psealand3n@java.com,7 West Crossing,Trenton,NJ,8650
134,191,4/19/2019,1,"$20,000.00","$8,500.00",135,Brainlounge,Capital Goods,Electrical Products,jcarnson3q@rambler.ru,9 Pierstorff Lane,Denton,TX,76205
143,321,1/23/2019,1,"$15,000.00","$5,900.00",144,Centizu,Technology,EDP Services,scamplejohn3z@unc.edu,72789 Arapahoe Pass,Phoenix,AZ,85035
156,616,1/31/2019,1,"$16,000.00","$23,200.00",157,Zava,Consumer Non-Durables,Plastic Products,aharfleet4c@cnn.com,5 Ryan Trail,Beaumont,TX,77713
163,697,9/12/2019,1,"$15,000.00","$13,400.00",164,Miboo,Capital Goods,Fluid Controls,esantus4j@163.com,9 Summer Ridge Lane,Sacramento,CA,94237
171,814,7/6/2019,1,"$49,000.00","$9,300.00",172,Brainsphere,Health Care,Medical/Dental Instruments,sassur4r@bloglovin.com,5881 Ruskin Circle,Portland,OR,97206
173,713,3/28/2019,1,"$52,000.00","$18,900.00",174,Nlounge,Health Care,Medical/Dental Instruments,cmullaly4t@cbslocal.com,671 Melvin Hill,Saint Cloud,MN,56398
183,944,3/20/2019,1,"$39,000.00","$9,600.00",184,Livefish,Finance,Major Banks,cmacrory53@ning.com,137 Harbort Way,Orlando,FL,32885
187,226,10/13/2019,1,"$77,000.00","$9,600.00",188,Topicblab,NaN,NaN,ctommei57@hc360.com,965 Columbus Park,Cincinnati,OH,45264
187,768,11/2/2019,1,"$94,000.00","$12,700.00",188,Topicblab,NaN,NaN,ctommei57@hc360.com,965 Columbus Park,Cincinnati,OH,45264
193,536,3/3/2019,1,"$44,000.00","$17,800.00",194,Meemm,Consumer Services,Real Estate Investment Trusts,jrobinson5d@zimbio.com,99 Vidon Pass,Atlanta,GA,31136
200,973,8/21/2019,1,"$47,000.00","$12,300.00",201,Thoughtstorm,Consumer Services,Real Estate Investment Trusts,cjahan5k@reddit.com,13 Lotheville Trail,Albuquerque,NM,87201

In [5]:
import re

for each in ['deposit', 'monthly_amt']:
    df.loc[:, each] = pd.to_numeric([re.sub('[^0-9.]', '', str(s)) for s in df[each]])

df

,contract_id,contract_start,contract_term,deposit,monthly_amt,customer_id,company,sector,industry,email,address,city,state,zip
1,41,5/31/2019,24,86000.0,11200.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,358,6/18/2019,13,74000.0,19000.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,400,8/11/2019,19,38000.0,8800.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,424,3/13/2019,15,77000.0,14300.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
1,438,10/16/2019,22,39000.0,20000.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,284,12/28/2019,17,78000.0,17600.0,201,Thoughtstorm,Consumer Services,Real Estate Investment Trusts,cjahan5k@reddit.com,13 Lotheville Trail,Albuquerque,NM,87201
200,540,4/17/2019,3,65000.0,9800.0,201,Thoughtstorm,Consumer Services,Real Estate Investment Trusts,cjahan5k@reddit.com,13 Lotheville Trail,Albuquerque,NM,87201
200,630,11/1/2019,12,85000.0,12600.0,201,Thoughtstorm,Consumer Services,Real Estate Investment Trusts,cjahan5k@reddit.com,13 Lotheville Trail,Albuquerque,NM,87201
200,862,10/2/2019,21,48000.0,6500.0,201,Thoughtstorm,Consumer Services,Real Estate Investment Trusts,cjahan5k@reddit.com,13 Lotheville Trail,Albuquerque,NM,87201
200,973,8/21/2019,1,47000.0,12300.0,201,Thoughtstorm,Consumer Services,Real Estate Investment Trusts,cjahan5k@reddit.com,13 Lotheville Trail,Albuquerque,NM,87201

In [6]:
df['contract_amount']= df['deposit'] + (df['contract_term'] * df['monthly_amt'])
df.head()

,contract_id,contract_start,contract_term,deposit,monthly_amt,customer_id,company,sector,industry,email,address,city,state,zip,contract_amount
1,41,5/31/2019,24,86000.0,11200.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,354800.0
1,358,6/18/2019,13,74000.0,19000.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,321000.0
1,400,8/11/2019,19,38000.0,8800.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,205200.0
1,424,3/13/2019,15,77000.0,14300.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,291500.0
1,438,10/16/2019,22,39000.0,20000.0,2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,479000.0

In [7]:

df['sector'] = df['sector'].fillna('')
df.loc[df['contract_term'] < 2]

,contract_id,contract_start,contract_term,deposit,monthly_amt,customer_id,company,sector,industry,email,address,city,state,zip,contract_amount
3,361,8/11/2019,1,49000.0,17900.0,4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667,66900.0
3,596,12/1/2019,1,19000.0,13500.0,4,Viva,Health Care,Major Pharmaceuticals,wgiovanitti3@nytimes.com,074 Center Place,Topeka,KS,66667,32500.0
15,84,4/4/2019,1,65000.0,22600.0,16,Kwinu,,NaN,alabetf@gov.uk,688 La Follette Park,Buffalo,NY,14215,87600.0
15,105,1/31/2019,1,61000.0,20200.0,16,Kwinu,,NaN,alabetf@gov.uk,688 La Follette Park,Buffalo,NY,14215,81200.0
16,211,6/15/2019,1,34000.0,14200.0,17,Plambee,Consumer Durables,Building Products,laupolg@earthlink.net,82 Bobwhite Point,Colorado Springs,CO,80915,48200.0
21,309,12/9/2019,1,44000.0,22700.0,22,Jabbercube,Health Care,Biotechnology: In Vitro & In Vivo Diagnostic S...,cgentlel@cnn.com,8275 Arizona Street,Odessa,TX,79764,66700.0
22,503,11/10/2019,1,64000.0,20400.0,23,Feedfire,Consumer Durables,Industrial Specialties,rrobynsm@ca.gov,777 La Follette Center,Saint Paul,MN,55114,84400.0
22,548,7/13/2019,1,55000.0,5300.0,23,Feedfire,Consumer Durables,Industrial Specialties,rrobynsm@ca.gov,777 La Follette Center,Saint Paul,MN,55114,60300.0
29,677,8/22/2019,1,24000.0,20400.0,30,Skyba,Consumer Services,Real Estate Investment Trusts,sfussent@skype.com,49623 Thompson Plaza,Miami Beach,FL,33141,44400.0
40,142,10/19/2019,1,25000.0,24800.0,41,Feedspan,Finance,Finance: Consumer Services,adauby14@soundcloud.com,633 Emmet Drive,Oakland,CA,94605,49800.0
51,628,7/8/2019,1,67000.0,24000.0,52,Jabbertype,,NaN,ycole1f@facebook.com,859 Summer Ridge Alley,Topeka,KS,66642,91000.0
52,556,6/12/2019,1,53000.0,8600.0,53,Centidel,Finance,Major Banks,fsutherby1g@reuters.com,93 Melvin Park,San Francisco,CA,94164,61600.0
53,473,5/10/2019,1,22000.0,8100.0,54,JumpXS,Consumer Services,RETAIL: Building Materials,ljarville1h@zdnet.com,8 Pennsylvania Trail,Gaithersburg,MD,20883,30100.0
55,393,6/3/2019,1,60000.0,22400.0,56,Twitternation,Finance,Finance: Consumer Services,nchillingsworth1j@mysql.com,8 Donald Plaza,Lansing,MI,48956,82400.0
55,653,11/28/2019,1,77000.0,5500.0,56,Twitternation,Finance,Finance: Consumer Services,nchillingsworth1j@mysql.com,8 Donald Plaza,Lansing,MI,48956,82500.0
60,23,7/13/2019,1,29000.0,21400.0,61,Bubblemix,Consumer Services,Real Estate Investment Trusts,rarlt1o@seattletimes.com,5498 Steensland Point,Shawnee Mission,KS,66276,50400.0
62,486,10/7/2019,1,68000.0,24900.0,63,Camimbo,Consumer Services,Homebuilding,gkellaway1q@nifty.com,545 Anderson Street,Las Vegas,NV,89166,92900.0
62,964,6/3/2019,1,37000.0,17700.0,63,Camimbo,Consumer Services,Homebuilding,gkellaway1q@nifty.com,545 Anderson Street,Las Vegas,NV,89166,54700.0
64,186,3/11/2019,1,57000.0,23100.0,65,Avamm,Technology,Advertising,gpavyer1s@discuz.net,81 Ludington Way,Atlanta,GA,31119,80100.0
66,301,12/9/2019,1,14000.0,15700.0,67,Skinix,Technology,Semiconductors,ilernihan1u@friendfeed.com,142 Towne Road,Fort Worth,TX,76105,29700.0
70,352,3/24/2019,1,37000.0,17900.0,71,Thoughtstorm,Consumer Services,Services-Misc. Amusement & Recreation,mwilliams1y@e-recht24.de,65 Tony Plaza,Miami,FL,33129,54900.0
70,665,9/27/2019,1,22000.0,24300.0,71,Thoughtstorm,Consumer Services,Services-Misc. Amusement & Recreation,mwilliams1y@e-recht24.de,65 Tony Plaza,Miami,FL,33129,46300.0
77,448,10/27/2019,1,62000.0,16400.0,78,JumpXS,,NaN,dphette25@foxnews.com,973 Ridgeway Pass,Columbus,OH,43268,78400.0
80,758,1/24/2019,1,28000.0,7000.0,81,Gigazoom,Consumer Services,Hotels/Resorts,oscoates28@cnet.com,21814 Waubesa Plaza,Oklahoma City,OK,73109,35000.0
81,656,2/1/2019,1,45000.0,15700.0,82,Edgeify,,NaN,dcoolahan29@vistaprint.com,22 Anniversary Pass,Raleigh,NC,27635,60700.0
83,420,4/15/2019,1,71000.0,12000.0,84,Photojam,,NaN,jbosward2b@china.com.cn,237 Farmco Street,Chicago,IL,60624,83000.0
83,956,8/18/2019,1,43000.0,21400.0,84,Photojam,,NaN,jbosward2b@china.com.cn,237 Farmco Street,Chicago,IL,60624,64400.0
88,374,5/1/2019,1,32000.0,7000.0,89,Miboo,Technology,Semiconductors,ckirtley2g@ucoz.com,86234 Moland Point,Olympia,WA,98506,39000.0
92,760,12/28/2019,1,31000.0,23900.0,93,Bluezoom,Public Utilities,Telecommunications Equipment,ybrickhill2k@whitehouse.gov,19 Vidon Place,Pasadena,CA,91186,54900.0
93,375,3/16/2019,1,39000.0,8000.0,94,Aivee,Public Utilities,Telecommunications Equipment,wlidden2l@earthlink.net,19 Portage Parkway,Muncie,IN,47306,47000.0
95,85,8/13/2019,1,17000.0,21700.0,96,Devify,Finance,Major Banks,apittman2n@i2i.jp,0 Stoughton Street,Schenectady,NY,12325,38700.0
96,257,7/2/2019,1,96000.0,23200.0,97,Photospace,Consumer Services,Services-Misc. Amusement & Recreation,tgibbin2o@dion.ne.jp,314 Kim Junction,Seattle,WA,98166,119200.0
98,776,7/12/2019,1,86000.0,20900.0,99,Linktype,Technology,EDP Services,jlackner2q@gmpg.org,6721 Kenwood Lane,Pittsburgh,PA,15279,106900.0
107,278,4/21/2019,1,94000.0,17400.0,108,Feedspan,Consumer Non-Durables,Electronic Components,mmacgowan2z@unicef.org,4964 Muir Lane,New York City,NY,10165,111400.0
111,132,8/14/2019,1,93000.0,6000.0,112,Dablist,,NaN,kcushion33@statcounter.com,09 Waubesa Hill,Tampa,FL,33633,99000.0
121,491,11/6/2019,1,12000.0,9600.0,122,Skinder,Health Care,Major Pharmaceuticals,cstuttard3d@businesswire.com,7 Chive Drive,Schenectady,NY,12305,21600.0
128,248,3/17/2019,1,19000.0,6300.0,129,Edgetag,,NaN,hwinship3k@rediff.com,32 Pennsylvania Point,Las Vegas,NV,89155,25300.0
129,388,5/9/2019,1,59000.0,8200.0,130,Gabvine,Health Care,Medical/Dental Instruments,iburgwyn3l@umn.edu,8557 Myrtle Trail,New York City,NY,10029,67200.0
131,492,5/22/2019,1,81000.0,13200.0,132,Flashspan,Finance,Savings Institutions,psealand3n@java.com,7 West Crossing,Trenton,NJ,8650,94200.0
134,191,4/19/2019,1,20000.0,8500.0,135,Brainlounge,Capital Goods,Electrical Products,jcarnson3q@rambler.ru,9 Pierstorff Lane,Denton,TX,76205,28500.0
143,321,1/23/2019,1,15000.0,5900.0,144,Centizu,Technology,EDP Services,scamplejohn3z@unc.edu,72789 Arapahoe Pass,Phoenix,AZ,85035,20900.0
156,616,1/31/2019,1,16000.0,23200.0,157,Zava,Consumer Non-Durables,Plastic Products,aharfleet4c@cnn.com,5 Ryan Trail,Beaumont,TX,77713,39200.0
163,697,9/12/2019,1,15000.0,13400.0,164,Miboo,Capital Goods,Fluid Controls,esantus4j@163.com,9 Summer Ridge Lane,Sacramento,CA,94237,28400.0
171,814,7/6/2019,1,49000.0,9300.0,172,Brainsphere,Health Care,Medical/Dental Instruments,sassur4r@bloglovin.com,5881 Ruskin Circle,Portland,OR,97206,58300.0
173,713,3/28/2019,1,52000.0,18900.0,174,Nlounge,Health Care,Medical/Dental Instruments,cmullaly4t@cbslocal.com,671 Melvin Hill,Saint Cloud,MN,56398,70900.0
183,944,3/20/2019,1,39000.0,9600.0,184,Livefish,Finance,Major Banks,cmacrory53@ning.com,137 Harbort Way,Orlando,FL,32885,48600.0
187,226,10/13/2019,1,77000.0,9600.0,188,Topicblab,,NaN,ctommei57@hc360.com,965 Columbus Park,Cincinnati,OH,45264,86600.0
187,768,11/2/2019,1,94000.0,12700.0,188,Topicblab,,NaN,ctommei57@hc360.com,965 Columbus Park,Cincinnati,OH,45264,106700.0
193,536,3/3/2019,1,44000.0,17800.0,194,Meemm,Consumer Services,Real Estate Investment Trusts,jrobinson5d@zimbio.com,99 Vidon Pass,Atlanta,GA,31136,61800.0
200,973,8/21/2019,1,47000.0,12300.0,201,Thoughtstorm,Consumer Services,Real Estate Investment Trusts,cjahan5k@reddit.com,13 Lotheville Trail,Albuquerque,NM,87201,59300.0

In [13]:
# this is how I will calculate total sales by state with the groupby function 

df.groupby('state').agg({'contract_id':'count', 'company':pd.Series.nunique})

       contract_id  company
state
AK               7        1
AL               6        1
AR               6        1
AZ              22        5
CA              83       16
CO              30        6
CT              10        2
DC              27        8
DE              18        3
FL              73       15
GA              15        4
ID              10        3
IL              22        4
IN              10        3
KS              34        7
KY               3        1
LA              32        6
MA              10        1
MD              19        4
ME              10        1
MI              16        4
MN              18        3
MO              25        5
MS               1        1
NC              23        4
NE              12        3
NJ               5        1
NM               7        1
NV              15        2
NY              58       11
OH              37        6
OK              25        5
OR              31        5
PA              36        7
SC               5        1
TN              26        4
TX             110       20
VA              28        7
WA              38        9
WI              31        6
WV               6        1

In [16]:
df.loc[df['state'] == 'TX', 'company'].unique()

array(['Teklist', 'Meedoo', 'Jabbercube', 'Midel', 'Innotype', 'Eimbee',
       'Skinix', 'Trilia', 'Vinder', 'Avaveo', 'Skiptube', 'Flashset',
       'Gigashots', 'Brainlounge', 'Wikibox', 'Twitterbeat', 'Omba',
       'Zava', 'Topicshots', 'Mymm'], dtype=object)

In [17]:

df['contract_amount'] = df['deposit']+ (df['contract_term'] * df['monthly_amt'])
df.head()

,contract_id,contract_start,contract_term,deposit,monthly_amt,customer_id,company,sector,industry,email,address,city,state,zip,contract_amount
1,41,5/31/2019,24,"$86,000.00","$11,200.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,"$86,000.00$11,200.00$11,200.00$11,200.00$11,20..."
1,358,6/18/2019,13,"$74,000.00","$19,000.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,"$74,000.00$19,000.00$19,000.00$19,000.00$19,00..."
1,400,8/11/2019,19,"$38,000.00","$8,800.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,"$38,000.00$8,800.00$8,800.00$8,800.00$8,800.00..."
1,424,3/13/2019,15,"$77,000.00","$14,300.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,"$77,000.00$14,300.00$14,300.00$14,300.00$14,30..."
1,438,10/16/2019,22,"$39,000.00","$20,000.00",2,Izio,Energy,Oil & Gas Production,farlet1@comcast.net,15360 Village Green Street,Spokane,WA,99252,"$39,000.00$20,000.00$20,000.00$20,000.00$20,00..."

# Conclusion 
## Where Headerquarters Should Be: 
Based off the above data it is clear that Texas does the most business, yet that is not where they should put their headquarters. With further analysis it is evident that the company should be palcing there headquarters in Washington. They have the most contracts with the most reoccuring renewals. This is why it makes the most sense to have the headquarters in Washington.